### ISSUE TITLE
Error : when executing `run_postprocessing.py` 

### ISSUE THREAD

**Issue by foufa89** [ash-aldujaili/BMOBench#8]
Hi,

 I Got this error when executing `run_postprocessing.py`. 

![image](https://user-images.githubusercontent.com/45772169/57533276-ac27ce80-733d-11e9-85d2-dada447b5e75.png)
`left==rigth`, is it a precision problem in this part of `fancyplot_bigFont.py`?

I think, probably, `np.arange` works on a small scale 

![image](https://user-images.githubusercontent.com/45772169/57533923-21e06a00-733f-11e9-8ba7-f4bfd300e903.png)

How we can fix it?
PS: for the epsilon, IGD, and HV indicators we don't have this error message, as it's shown on the figure it appears with GD indicator

**Comment by ash-aldujaili** [comment]
Hi @foufa89, could you provide more context to the problem? Did you generate both HV and EPS results for your experiments?

I think this from the README is relevant to the problem:

```
All the quality indicators are computed in this stage except for the hypervolume (hv) indicator. If you want to include it in the processing, you have to execute step 6 of MATLAB Experiment procedure (above).
```

**Comment by foufa89** [comment]
Hi @ash-aldujaili 
Thanks for your prompt reply,
Yes, HV results are generated and the `run_postprocessing` works for `indicators = ['eps', 'igd', 'hv']`
This problem appears with GD indicator, separable functions (I think)

**Comment by ash-aldujaili** [comment]
Hey @foufa89 is the issue fixed?

**Comment by foufa89** [comment]
Hey @ash-aldujaili, Ramadan Mubarak;

Not really, Now the post-processing is completed,  but the resulting GD-plots are stable horizontal lines.

**Comment by ash-aldujaili** [comment]
Thank you.

It is possible the algorithm is not hitting any of the GD targets. Consequently, its profile will be flat. Try giving the algorithm more function evaluations.

**Comment by foufa89** [comment]
Ok, I will try this.
